Implement webhooks for catching stripe events
ZeeshanAzhar23/Billing_and_Recurring_Payment_System pull request #10
Opened 2022-07-28 21:18 UTC by ZeeshanAzhar23

2022-07-29 19:28 UTC, Muhammad-Asim-khalid requested changes

2022-07-29 19:28 UTC, Muhammad-Asim-khalid commented on app/controllers/webhooks_controller.rb
> +      #  return if !User.exists?(event.data.object.client_reference_id)
remove commented code.

2022-07-29 19:28 UTC, Muhammad-Asim-khalid commented on app/controllers/webhooks_controller.rb
> +
this is an empty when statement, remove this if not required.

2022-07-29 19:28 UTC, Muhammad-Asim-khalid commented on test/controllers/features_controller_test.rb
> +end
don't need this file.

2022-07-29 19:28 UTC, Muhammad-Asim-khalid commented on test/controllers/home_controller_test.rb
> +end
delete this fle

2022-07-29 19:28 UTC, Muhammad-Asim-khalid commented on test/controllers/plans_controller_test.rb
> +end
delete all test files

2022-08-03 08:12 UTC, ZeeshanAzhar23 reviewed
Kindly review the changes

2022-08-03 08:21 UTC, Muhammad-Asim-khalid approved these changes

2022-08-03 12:15 UTC, merged