Implement billing functionality
ZeeshanAzhar23/Billing_and_Recurring_Payment_System pull request #11
Opened 2022-07-28 21:24 UTC by ZeeshanAzhar23

2022-07-29 19:30 UTC, Muhammad-Asim-khalid requested changes

2022-07-29 19:30 UTC, Muhammad-Asim-khalid commented on app/views/devise/registrations/edit.html.erb
> +<%# <%end%>
remove commented code

2022-08-03 08:13 UTC, ZeeshanAzhar23 reviewed
kindly review the changes

2022-08-03 08:21 UTC, Muhammad-Asim-khalid approved these changes

2022-08-03 12:15 UTC, merged