Add the functionality of plans
ZeeshanAzhar23/Billing_and_Recurring_Payment_System pull request #3
Opened 2022-07-28 20:20 UTC by ZeeshanAzhar23

2022-07-29 16:04 UTC, Muhammad-Asim-khalid requested changes

2022-07-29 16:04 UTC, javier459 commented on app/controllers/plans_controller.rb
> +  before_action :find_plan, only: [:show,:edit,:update,:destroy]
spacing issue

2022-07-29 16:04 UTC, javier459 commented on app/controllers/plans_controller.rb
> +  @plans=Plan.all
spacing issue

2022-07-29 16:04 UTC, javier459 commented on app/controllers/plans_controller.rb
> +    @plan=Plan.new
spacing issue

2022-07-29 16:04 UTC, javier459 commented on app/controllers/plans_controller.rb
> +    @plan=Plan.create(plan_params)
spacing issue

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/controllers/plans_controller.rb
> +    @features = Plan.find(params[:id]).features.new
we already have @plan accessible here, we can use `@plan.features.new` here

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/controllers/plans_controller.rb
> +  end
add private block and then use these methods

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/controllers/plans_controller.rb
> +    #Strip::Price.delete(@stripe_price_id)
remove commented code

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/models/plan.rb
> +  end
create a separate function for this and call that function in callback

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/models/plan.rb
> +  # end
remove commented code

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/views/plans/index.html.erb
> +    <% end %>
use partial here to remove the loop.

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/views/users/index.html.erb
> +    <% end %>
use partial here

2022-07-29 16:04 UTC, Muhammad-Asim-khalid commented on app/views/users/old_code.html.erb
> +<%# <%end%>
remove commented code.

2022-08-03 07:57 UTC, ZeeshanAzhar23 reviewed
Kindly Review the changes made

2022-08-03 07:58 UTC, Muhammad-Asim-khalid approved these changes

2022-08-03 08:15 UTC, merged