Add Features implementation for plans
ZeeshanAzhar23/Billing_and_Recurring_Payment_System pull request #5
Opened 2022-07-28 20:37 UTC by ZeeshanAzhar23

2022-07-29 19:14 UTC, Muhammad-Asim-khalid requested changes

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/controllers/features_controller.rb
> +  before_action :find_feature, only: [:show,:edit,:destroy,:update]
spacing issue

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/controllers/features_controller.rb
> +  @features=Plan.find(params[:plan_id]).features
spacing issue

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/controllers/features_controller.rb
> +    @feature=@plan.features.new
spacing issue

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/controllers/features_controller.rb
> +    id=@feature.plan_id
spacing issue

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/controllers/features_controller.rb
> +    @feature=@plan.features.find(params[:id])
spacing issue

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/controllers/features_controller.rb
> +  private def find_feature
convert into private block

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/models/feature.rb
> +
remove extra empty lines

2022-07-29 19:14 UTC, Muhammad-Asim-khalid commented on app/views/features/index.html.erb
> +    <% end %>
use partial here

2022-08-03 07:59 UTC, Muhammad-Asim-khalid approved these changes

2022-08-03 08:03 UTC, ZeeshanAzhar23 reviewed
Kindly review the changes

2022-08-03 08:14 UTC, merged