Add checkout feature through stripe
ZeeshanAzhar23/Billing_and_Recurring_Payment_System pull request #8
Opened 2022-07-28 21:01 UTC by ZeeshanAzhar23

2022-07-29 19:24 UTC, Muhammad-Asim-khalid requested changes

2022-07-29 19:24 UTC, Muhammad-Asim-khalid commented on app/controllers/purchase/checkouts_controller.rb
> + # before_action :retrieve_price_id, only: [:create]
remove commented code.

2022-07-29 19:24 UTC, Muhammad-Asim-khalid commented on app/controllers/purchase/checkouts_controller.rb
> +      price=@plan.price_id
spacing issue

2022-07-29 19:24 UTC, Muhammad-Asim-khalid commented on app/controllers/purchase/checkouts_controller.rb
> +      #price = params[:pricing_id]
remove commented code

2022-07-29 19:24 UTC, Muhammad-Asim-khalid commented on app/controllers/purchase/checkouts_controller.rb
> +          #price: price,
remove commented code.

2022-07-29 19:24 UTC, Muhammad-Asim-khalid commented on app/controllers/purchase/checkouts_controller.rb
> +  # end
remove commented code

2022-08-03 08:04 UTC, ZeeshanAzhar23 reviewed
Kindly review the changes

2022-08-03 08:21 UTC, Muhammad-Asim-khalid approved these changes

2022-08-03 12:15 UTC, merged